services:
  reanalysis:
    container_name: ${CONTAINER_NAME}
    build: .
    image: ${IMAGE_NAME}
    command: >
      postgres
      -c min_wal_size=4GB
      -c max_wal_size=16GB
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - /private/:/private/
  pgAdmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root 
    ports:
      - "8099:80"
